### ISSUE TITLE
Input format for PCVs

### ISSUE THREAD

**Issue by fabianmoss** [DCMLab/MIDFT#17]
Currently, the input only allows for 
- pitch-class vectors
- pitch-class sets
and both have to be entered without using spaces. 

I think the input should be a bit more forgiving, e.g. accepting both `{0,4,7}` and `{0, 4, 7}` (with any number of white spaces).

**Comment by fabianmoss** [comment]
We can also think about allowing multisets to be entered, e.g. 
`{0,0,0,0,4,4,7,7,7}` could internally be converted to `(4,0,0,0,2,0,0,3,0,0,0,0)`.

**Comment by dharasim** [comment]
This is implemented now, right?

**Comment by heyGio** [comment]
Yes, it is implemented! I might forgot to close the issue
