### ISSUE TITLE
Chromatic vector Ω

### ISSUE THREAD

**Issue by fabianmoss** [DCMLab/MIDFT#19]
This vector is a prototype in all coefficients but is colored differently (dark teal). I don't think it needs a special color, in particular because it covers the white center of the plot. I think it should be a grey circle as the other prototypes as well.

**Comment by heyGio** [comment]
The teal dot is related to the pitch class vector generated by the midi device. Since nothing is being played, the coefficients are all in the origin. What i could do is to plot the teal dot only if the application detect a midi device. @fabianmoss

**Comment by fabianmoss** [comment]
Yes, I think that would be a good solution. When nothing is played, nothing should be displayed.
