### ISSUE TITLE
Prototypes' labels are not placed properly

### ISSUE THREAD

**Issue by heyGio** [DCMLab/MIDFT#2]
Prototypes' labels on the circumference should be placed outside the circle for a better visualization.
Offsets between the labels and the actual circles of the prototypes are not precise.

**Comment by dharasim** [comment]
Yes, that's better

**Comment by fabianmoss** [comment]
I think it's not completely fixed yet. For example, the whole-tone labels are too close to the circles in the sixth coefficient, as well as the C°7 and C#°7 sevenths chords in the fourth coefficient.
