### ISSUE TITLE
The resolution symbols are not displayed properly

### ISSUE THREAD

**Issue by dharasim** [DCMLab/MIDFT#22]
On macOS, symbols like the half note are not displayed properly. This holds for all browsers I tried: Firefox, Chrome, and Safari.

<img width="389" alt="Screenshot 2021-11-16 at 17 15 14" src="https://user-images.githubusercontent.com/19477065/142022994-be80976a-183e-4e4e-98ce-ee5f60283789.png">

**Comment by heyGio** [comment]
Should be solved now! Tested with Chrome on macOS @dharasim

**Comment by dharasim** [comment]
Indeed, it works now 👍 
I tested it with chrome and firefox.
